### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by HeyImMarkus** [IESEG-Java-Web-dev/crispy-pancake#25]
The css has been merged but the " Location " at the top of the page still has a different format than the other pages. I dont know why...

And second issue is the fact that there is a sort of a shadow box between the container of Quentin and Ambroise.
The shadow box appears when I put the container of Quentin at the middle of the page.
When it was on the left side, using float:left. The shadow box was not there so it only appears when the container is put "arbitrarely" in the middle.

**Comment by HeyImMarkus** [comment]
The second issue ('shadow box') is fixed now !

But the first issue remains ('Location in the wrong format')

**Comment by qblanco** [comment]
I looked into it but doesn't understand either why location is in the wrong format
It looks like after inspecting the eleemtn that they don't rely on the same stylesheet, maybe because of bootstrap
![image](https://user-images.githubusercontent.com/65412377/116814626-2de01a80-ab5a-11eb-8efd-cb8d2b9544cb.png)

![image](https://user-images.githubusercontent.com/65412377/116814604-1dc83b00-ab5a-11eb-88fe-5bfbddc4ab49.png)

**Comment by qblanco** [comment]
I think we can solve the issue by loading the bootstrap library in the about page

**Comment by qblanco** [comment]
#26
